### ISSUE TITLE
Missing ability to use secure connection 

### ISSUE THREAD

**Issue by jzoran05** [bricaud/graphexp#1]
Any chance you can add support for using authenticated connection to gremlin server endpoint?

**Comment by bricaud** [comment]
It is in the todo list but not the priority.  It should be done by changing the Websocket connection in graphioGremlin.js from ws to wss and adding the credentials in some way. There is an example of connection from js here https://github.com/jbmusso/gremlin-javascript/blob/master/src/WebSocketGremlinConnection.js . I will have a look at it next month.

**Comment by bricaud** [comment]
Help wanted on this topic! I had a look and it is quite complex to implement. Gremlin-javascript handles it but I do not want to use node.js for Graphexp.

**Comment by 1-santosh** [comment]
Could you help in connecting graphic to Neptune endpoint . currently it is giving time out error.please help me
