### ISSUE TITLE
jQuery breaks under https. "src" should be protocol relative.

### ISSUE THREAD

**Issue by preston** [bricaud/graphexp#100]
This line breaks when running under https: https://github.com/bricaud/graphexp/blob/babed1089ce8456167df1ef0be1976fab002d690/graphexp.html#L13

It should be this instead:

    <script src="//code.jquery.com/jquery-3.2.1.min.js"></script>

**Comment by bricaud** [comment]
ok, thanks, 
I changed http to https for jquery and d3 urls.
