### ISSUE TITLE
Error retrieving data

### ISSUE THREAD

**Issue by ghost** [bricaud/graphexp#102]
java.lang.IllegalStateException: The child traversal of [GraphStep(vertex,[4b833f43-2d79-48af-8615-9f7ec3f834fc]), PropertyMapStep(value)] was not spawned anonymously - use the __ class rather than a TraversalSource to construct the child traversal
neptune_1     | 	at org.apache.tinkerpop.gremlin.process.traversal.Bytecode.convertArgument(Bytecode.java:302)
neptune_1     | 	at org.apache.tinkerpop.gremlin.process.traversal.Bytecode.flattenArguments(Bytecode.java:287)
neptune_1     | 	at org.apache.tinkerpop.gremlin.process.traversal.Bytecode.addStep(Bytecode.java:94)
neptune_1     | 	at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal.inject(GraphTraversal.java:1287)
neptune_1     | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
neptune_1     | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
neptune_1     | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
neptune_1     | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
neptune_1     | 	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
neptune_1     | 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:188)
neptune_1     | 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
neptune_1     | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
neptune_1     | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
neptune_1     | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
neptune_1     | 	at Script6.run(Script6.groovy:1)
neptune_1     | 	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:676)
neptune_1     | 	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:378)
neptune_1     | 	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
neptune_1     | 	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:272)
neptune_1     | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
neptune_1     | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
neptune_1     | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
neptune_1     | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
neptune_1     | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
neptune_1     | 	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by sumitsharansatsangi** [comment]
This error is occurring because, this is still using 3.4.* . This library must be update to be used with 3.5.1, which is the latest version.  If you can change the syntax compatible to gremlin 3.5.1 , This error will probably won't occur.

**Comment by ailntps** [comment]
update line 184&186 `traversal_source` to `__`  in`/scripts/graphioGremlin.js`

**Comment by pimjansen** [comment]
Is this still an open topic? Or are there any alternatives in browser/exploring a graph database (for free) in development?

**Comment by bricaud** [comment]
I need to create an option where `traversal_source`is replaced by `__` when choosing version 3.5. So here the PR is not complete, if I merge, the code wont run for people using earlier versions.

**Comment by bricaud** [comment]
I merged the PR! Thanks a lot!
