### ISSUE TITLE
Does this project support multiple edges between 2 nodes.

### ISSUE THREAD

**Issue by smandala** [bricaud/graphexp#13]
My graph has multiple edges between 2 vertices. Does this project support showing this information?

**Comment by bricaud** [comment]
I have never tried but in principle, yes. However there might be some bugs due to the diplicated neighbors he will get from the request to the DB. 
Have a try an let me know.
It should be easy to adapt and correct it, if it is not displaying properly the links.

**Comment by smandala** [comment]
Thanks for your prompt response. I have tried and it doesn't work. I see only one edge between the vertices but I observe both labels written on the edge. (one on top of another making it blurry)

**Comment by bricaud** [comment]
ok I see. So they are displayed, but one on top of the other, which is not very convenient. I will think about a correction. Thanks for trying.

**Comment by nikhilv14** [comment]
+1 and implementing curved edges may be solution to display multiple edges

**Comment by smuaq** [comment]
+1 having the same issue, any help appreciated

**Comment by bricaud** [comment]
Solved with #50
