### ISSUE TITLE
Copying data from browser doesn't seem to be possible

### ISSUE THREAD

**Issue by sahilsareen** [bricaud/graphexp#17]
Although the `Item Info` is shown on the right, on trying to select the data from there I end up moving the canvas around instead of selecting/copying the data.
I couldn't find an easy way to copy data from the canvas as I explore the graph. I believe there is a problem with the "div" of the graph being on top of the "div" for the side bar.

**Comment by bricaud** [comment]
The new merge solves the problem. Thanks @Peter-SouzaConsulting .
