### ISSUE TITLE
New feature - filter by edge label to explore

### ISSUE THREAD

**Issue by grreeenn** [bricaud/graphexp#19]
Hi Benjamin,

Thank you for the project.
For my usage case I needed to filter the graph exploration by edge label. I've implemented it (was not a big deal) - the question is, do you want it to be a part of a project, and if yes - how do I contribute it?

**Comment by bricaud** [comment]
Great, that would be an nice thing to have.
You can make a pull request.
Thanks

**Comment by grreeenn** [comment]
perfect, willdo soon :)
new field also messes the header a bit, so I'll [gridify](https://www.w3schools.com/css/css_grid.asp) it.

**Comment by grreeenn** [comment]
seems that I don't have write access to the repo... can't neither create branch nor push
it's my first contribution on github, could you please point me on what I have missed?

**Comment by bricaud** [comment]
Hi Gregory,
You have to fork the repo, then it is saved in your github account. Clone
the version you have (the fork), do the modifications, commit them and push
them to your fork. Then make a pull request.

https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Benjamin

2018-04-09 17:03 GMT+02:00 Gregory Zhukovsky <notifications@github.com>:

**Comment by grreeenn** [comment]
Thank you for your patience :) PR's here.

I think that the logical continuation of it will be an ability to filter edge direction also

**Comment by bricaud** [comment]
The code looks great! Thanks a lot! I will test it asap and merge the changes if everything is fine.
