### ISSUE TITLE
Enhancement: Add vertex icon support

### ISSUE THREAD

**Issue by dmoore247** [bricaud/graphexp#26]
Add ability to map gremlin vertex labels to node icons to provide a richer visual experience. This issue is to track the requirements & design aspects of the enhancement.

**Comment by dmoore247** [comment]
http://visjs.org/ has recently added font icon support ([Node icon example])(http://visjs.org/examples/network/nodeStyles/customGroups.html). The visualization module inspects the node object looking for a `group` property. The group property is user definable, identifying a shape or font-icon, color, size...

I imagine we provide for a label to group to icon mapping definition file in the scripts directory that the end user is instructed to override? Ideas?

**Comment by bricaud** [comment]
It is also possible with D3.js (adding images too):
https://stackoverflow.com/questions/18416749/adding-fontawesome-icons-to-a-d3-graph
It seems to be an additional text attached to the node.
