### ISSUE TITLE
Prevent fading out of nodes entirely

### ISSUE THREAD

**Issue by k4rthikr** [bricaud/graphexp#34]
Been playing with the graphexp code for a bit, and I can't make it stop fading away the expanded graph (or forest) once I make a few clicks. Sure, I can pin specific nodes, but I want to basically pin "all" the nodes and edges that I have explored as of now.

Any ideas on how to build that? Is it already supported?

**Comment by bricaud** [comment]
Yes sure, you can increase the number of layers in the box "number of layers".
