### ISSUE TITLE
Use curved-links d3 template

### ISSUE THREAD

**Issue by k4rthikr** [bricaud/graphexp#35]
https://bl.ocks.org/mbostock/4600693

Can we make GraphExp generate something that looks like that? Pointers appreciated, I'll try to implement if possible.

**Comment by bricaud** [comment]
Yes it should be possible. The edges are made using Bezier curves, see
https://www.dashingd3js.com/svg-paths-and-d3js
It is encoded in the function "positionLink" ( with the 'M' and 'S' properties) in the link you give. So the function "ticked" of Graphexp, in graph_viz.js could be modified to call "positionLink".
However, to get a nice curve in the D3 example, an invisible intermediate node is added, so you also have to modify the list of links. The "bilinks" data is added. I can't see if this is easy to implement, but you can try.
If you implement it and want to make a PR, please try to design the edge shape as an option (straight or curved) that can be chosen in the config file.

**Comment by agussman** [comment]
I'll take a stab at this for Hacktober!

**Comment by bricaud** [comment]
`_links` is the d3.js object with all active links (the ones that are not frozen), `_Links` is the list with the data for each link (just the data given by the graphDB) and `edgepaths` is involved in the display of the link properties on the graph (next to the edge). I do not remember exactly why right now, have a look here: http://bl.ocks.org/jhb/5955887
all_links is used when doing the transition when new data is coming and has to be added. I should change the name. It the set of all active links + the ones that have just been added from the DB query.

**Comment by bricaud** [comment]
Any help appreciated. This could also solve issue #13

**Comment by bricaud** [comment]
Solved with #50
