### ISSUE TITLE
 _table_Graphinfo.select is not a function

### ISSUE THREAD

**Issue by erandal** [bricaud/graphexp#36]
infobox.js:61 Uncaught TypeError: _table_Graphinfo.select is not a function
    at Object.display_graph_info (infobox.js:61)
    at handle_server_answer (graphioGremlin.js:318)
    at WebSocket.ws.onmessage (graphioGremlin.js:280)
display_graph_info @ infobox.js:61
handle_server_answer @ graphioGremlin.js:318
ws.onmessage @ graphioGremlin.js:280

Hi, i am using graphexp with JanusGraph & when i want to load the Graph Info i get this error in the console.

I don't program in JavaScript so i can't really understand what that means.
I have checked the connection to the gremlin-server embedded in janusgraph & it returns the right content. (The GodGraph)

**Comment by bricaud** [comment]
Thanks for your comment @erandal. You just spotted a small bug. I have corrected it, it should be fine now.
