### ISSUE TITLE
Different front ends for Graphexp

### ISSUE THREAD

**Issue by bricaud** [bricaud/graphexp#39]
Below you can give some remarks, comments and feedbacks on the different frontends that Graphexp has or could have.

**Comment by Miroka96** [comment]
The Bootstrap experience seems much smarter and so far I have not found strange behaviours. Graphs with few hundred vertices and edges have been shown without any problems.

**Comment by ddmx** [comment]
I update graphexp to fit gremlin server 3.4 at [ddmx/graphexp](https://github.com/ddmx/graphexp). So we can find properties  when clicking on the vertex.
