### ISSUE TITLE
Only one edge is shown

### ISSUE THREAD

**Issue by RaulGuo** [bricaud/graphexp#47]
I tried to use graphexp to show my graph, but when the result was shown in the page, there is only one edge shown though the vertices are all shown as it should be. But there should be more than that, I tried to debug and find the search is executed successfully and eight edges is retrieved in the result but only one is shown, what is the matter?
![image](https://user-images.githubusercontent.com/13598386/44388959-24562600-a55c-11e8-871d-f0b8e428ab6b.png)

**Comment by bricaud** [comment]
Difficult to say just from this.
If you click on the nodes that are supposed to have edges, do the edges appear?

**Comment by bricaud** [comment]
strange, I will have a look over the week end. What is the graph database you are using? Amazon Neptune, the default Gremlin server in-memory one or another?

**Comment by John-Boik** [comment]
I'm using janusgraph (0.3.0-hadoop2), with cassandra backend for storage (shipped with janusgraph). I use goblin via gremlin-python via gremlin server to manipulate the graph.

**Comment by bricaud** [comment]
I had a quick look but I can't figure out what is happening. When I look at the screenshot, the id of the edge should not be an object. Graphexp may be confused by the edge id, properties or configuration. Could you tell me what are the types of id and labels for the edges and nodes of your graph, and the types for their properties?
Is there something special written in the javascript console when the search button is clicked?

**Comment by bricaud** [comment]
@RaulGuo are you also using janusgraph ?

**Comment by John-Boik** [comment]
I'm using python goblin --> aiogremlin --> gremlin server --> janusgraph --> cassandra, all recent installs. Here is an example of the data I read into the graph using graphson:

{"id":{"@type":"g:Int32","@value":23},"label":"center",

"properties":{"name":[{"id":{"@type":"g:Int64","@value":10},"value":"bey","properties":{"ts_start":{"@type":"g:Date","@value":1430491502287},"inference":false}}]},

"outE":{"has_code":[{"id":{"@type":"g:Int32","@value":49},"inV":{"@type":"g:Int32","@value":9},"properties":{"ts_start":{"@type":"g:Date","@value":1430491502287},"ts_end":{"@type":"g:Date","@value":1432218900770},"inference":false}}]},

"inE":{"has":[{"id":{"@type":"g:Int32","@value":36},"outV":{"@type":"g:Int32","@value":1},"properties":{"ts_start":{"@type":"g:Date","@value":1430491502287},"ts_end":{"@type":"g:Date","@value":1432218900770},"inference":false}}]}}

The IDs for each node/edge are int32, the IDs for properties are int64. 

I can verify (see new screenshot) that the ID for a node is given as the correct integer, but as in the original screenshot, the ID for an edge is given as [object Object].  Further, for a node, the info box is not cut off and the full integer for the date can be seen.

![screenshot_2018-09-01_10-38-30](https://user-images.githubusercontent.com/22616258/44947614-1cf11100-add5-11e8-83e1-39c99419faff.png)

I don't see any messages in the cassandra.log or gremlin-server.log files that pertain to graphexp. I start the gremlin-server via scripts provided by Janusgraph. The server runs in the background, not in a command window.

**Comment by John-Boik** [comment]
There is nothing special in the browser console. I see, for example:

**Comment by John-Boik** [comment]
Also, could you include a button that turns off the layers-type visualization and simply keeps all loaded nodes and edges present, not matter what node is clicked? This would be helpful for visualizing small graphs, where the layers-type visualization is unnecessary (and for me, unwanted).

**Comment by bricaud** [comment]
To answer your two last questions: 

* for custom gremlin queries, It would require too much work for me at the moment unfortunately.
* to turn off the layers-type visulaization, you may tick the box "freeze exploration" or choose a large amount of layers (1000 for example).

**Comment by bricaud** [comment]
It may be a bug when handling the data recieved. @John-Boik could you uncomment the line 351 in graphoiGremlin.js (console.log(data)) and write what is displayed in the javascript browser console when you click on an edge?

**Comment by John-Boik** [comment]
I see that a large amount of info is written to the console, and each line has to be expanded manually (I don't see an expand all button). Is this enough info?
```
Navigated to file:///home/johnb/Devel/ETR/GRAPH_DB/visualize/graphexp/graphexp.html?ts=etrg
{…}
​
"@type": "g:List"
​
"@value": (4) […]
​​
0: (1) […]
​​​
0: {…}
​​​​
center: 13
​​​​
center_code: 17
​​​​
region: 5
​​​​
<prototype>: Object { … }
​​​
length: 1
​​​
<prototype>: Array []
​​
1: (1) […]
​​​
0: {…}
​​​​
"[ name ]": 35
​​​​
<prototype>: Object { … }
​​​
length: 1
​​​
<prototype>: Array []
​​
2: (1) […]
​​​
0: {…}
​​​​
has_center: 13
​​​​
has_center_code: 17
​​​​
<prototype>: Object { … }
​​​
length: 1
​​​
<prototype>: Array []
​​
3: (1) […]
​​​
0: {…}
​​​​
"[ inference , ts_end , ts_start ]": 30
​​​​
<prototype>: Object { … }
​​​
length: 1
​​​
<prototype>: Array []
​​
length: 4
​​
<prototype>: Array []
​
<prototype>: Object { … }
graphioGremlin.js:353:4
nodes = etrg.V().limit(50).toList();edges = etrg.V(nodes).aggregate('node').outE().as('edge').inV().where(within('node')).select('edge').toList();[nodes,edges] graphioGremlin.js:133:3
{…}
​
"@type": "g:List"
​
"@value": Array [ (35) […], (30) […] ]
​
<prototype>: Object { … }
graphioGremlin.js:353:4   
```

**Comment by John-Boik** [comment]
Here is an expansion of a vertex:

![screenshot_2018-09-02_10-53-14](https://user-images.githubusercontent.com/22616258/44957957-9b65b580-ae9e-11e8-821b-9c3849e1edf4.png)

Here is an expansion of an edge:

![screenshot_2018-09-02_10-54-24](https://user-images.githubusercontent.com/22616258/44957959-a587b400-ae9e-11e8-9343-9f643de390d4.png)

**Comment by bricaud** [comment]
Thanks!
I think the problem comes from the function idIndex in graphioGremlin.js line 416. It is tchecking if a edge id is already in the list of edges before adding it. Unfortunately the '==' works for integers but I guess not for objects. And in your database, the edge ids are objects. Try replacing the '==' by a '===' (strictly equal). If this does not work you will have to modify the line with `list[i].id.relationId === item.relationId `. I hope this will solve the problem! I think the object are always '==' even if they do not contain the same things,  so that the link is set to 'already exist' and it stop adding links after the first one.

**Comment by John-Boik** [comment]
Unfortunately, neither of those fixes worked.
`if (list[i].id === elem) return i;`
produces no error, but only one edge as before.

`if (list[i].id.relationId === item.relationId) return i;`
produces: ReferenceError: item is not defined[Learn More]

**Comment by bricaud** [comment]
right, sorry, try to put `elem.relationId` instead of `item.relationId`

**Comment by bricaud** [comment]
and maybe a `console.log(elem)` and a `console.log(list)` just before the for statement (in the function idIndex) to see what happens

**Comment by John-Boik** [comment]
With this code:
```
	function idIndex(list,elem) {
	  // find the element in list with id equal to elem
	  // return its index or null if there is no
	  for (var i=0;i<list.length;i++) {
		//if (list[i].id === elem) return i;
		console.log(elem);
		console.log(list);
		if (list[i].id.relationId === elem.relationId) return i;
```
I get only one node showing, no edges.

The console code is a bunch of arrays first:

![screenshot_2018-09-03_14-34-31](https://user-images.githubusercontent.com/22616258/45000019-0e4a5b80-af87-11e8-8a23-6336fe54f6dc.png)

Followed by arrays and edge relations:

![screenshot_2018-09-03_14-36-40](https://user-images.githubusercontent.com/22616258/45000025-1aceb400-af87-11e8-8065-5a884b80e554.png)

**Comment by CptQuint** [comment]
Any luck with this fix?

This is affecting me also (janusgraph-0.3.0-hadoop2).

**Comment by RaulGuo** [comment]
I have fixed the issue, this is caused by the differenct structure of returned vertex and edge. I have copies the repository to my own git and fix it now. The bug is caused by getting wrong attribute:
![image](https://user-images.githubusercontent.com/13598386/45156321-7069c180-b210-11e8-81ad-f47e6b601fdf.png)

You can see the detail of my [commit](https://github.com/RaulGuo/graphexp/commit/b5721e56a579b4d22a9d4b73096fb2b0a579f860)

But remember, just change the d.id to d.id.relationId of all the edge showing functions. I have added some other changes just to fit my own usage, just ignore those changes.

**Comment by bricaud** [comment]
Thanks everyone for your inputs. I have modified the code in `graphiogremlin.js` to test if the id is an object and if yes, it retrieves the id in id.relationId.
Could someone of you test it on your database and tell me if it works?

**Comment by RaulGuo** [comment]
@bricaud I have tried it in my case, it works for me. You can try it by  yourself. But I am sorry I cannot offer a version that only contains the changes for this issue, I fixed this and made some other changes to fix my own usage, and then commit them together. By the way, this project really helps me a lot, thank you very much.

**Comment by CptQuint** [comment]
Just to confirm @RaulGuo's change has fixed this issue for me.
