### ISSUE TITLE
GraphExp not showing any results

### ISSUE THREAD

**Issue by ErikvdVen** [bricaud/graphexp#49]
Hopefully somebody can help me out over here. Tried a lot of different datasets and it seems graphexp does connect to the database, because I do receive information about the database, except no nodes are being showed:
https://www.dropbox.com/s/dhskbmmpnitgsgb/Screen%20Shot%202018-09-19%20at%2020.33.49.png?dl=0

I tried executing the queries, which are showed in the chrome developer console, on the database directly and I do receive results. So or I forgot about something, or it doesn't work anymore.

**Comment by bricaud** [comment]
What happens when you click on the 'Search' button without filling any field? Do you get some nodes?

**Comment by ErikvdVen** [comment]
Nope, no nodes, I receive this error if I just hit the "Search" button without filling any fields:

```
Error during serialization: (was java.lang.IllegalStateException) (through reference chain: java.util.ArrayList[0]->java.util.ArrayList[0]->org.janusgraph.graphdb.relations.RelationIdentifier["inVertexId"])
```

I thought it was necassary to fill in some fields, but I just Googled a bit and it seems to be a gremlin-server error (makes sense because of the java error I suppose). Still don't know what the problem is exactly, any thoughts?

**Comment by bricaud** [comment]
thanks for the Docker image. I can't do it now but I will try to reproduce it tomorrow.
The last version of Janusgraph seems to have added changes in the way the results are sent. I have to figure that out.

**Comment by ErikvdVen** [comment]
Great! Looking forward to your findings. Thank you in advance for your help :)

**Comment by ErikvdVen** [comment]
What is kinda interesting is that I do see a response of nodes and edges on my serverside. It shows a warning as well: `in the request b979eeef-fb7b-4d97-b75c-0921551934e7 could not be serialized and returned.`. Which means the queries are actually executed by the server, but it's not able to return the request.

I wanted to use websockets for my own webinterface as well, but now I am using the official gremlin javascript package, provided by Apache, which is working. So I can't say what could actually be the problem, just the request or some server settings as well.

**Comment by bricaud** [comment]
I did not try the docker image yet. It seems that there are problems with serialization using the docker container provided in the link you give (as written in the readme of the github repo). Try to choose the graphexp option protocol 'REST' and try also to change the Gremlin version option from '3.3.*' to '3.2.* (it changes the protocol from graphson 3 to graphson 2). It might solve the problem. Also, can you choose another docker image?
