### ISSUE TITLE
UUID IdManagers appear to be unsupported

### ISSUE THREAD

**Issue by nhalase** [bricaud/graphexp#5]
I have a TinkerGraph where the vertex, edge and property IdManagers are all set to UUID. Queries fail due to an unexpected token. Looks like the UUIDs just need to be escaped. 

```
Script6.groovy: 1: unexpected token: b6e @ line 1, column 28.
nodes = g.V(ca5db130-996d-5b6e-9799-f357e8cc152d).as('node').both().as('node').select(all,'node').inject(g.V(ca5db130-996d-5b6e-9799-f357e8cc152d)).unfold()
```

**Comment by jdbranham** [comment]
Would probably be good to have a configuration option to set the ID type [string, number]

**Comment by bricaud** [comment]
The following test has been added:
```
if(isNaN(id)){
           id = "'"+id+"'";
           }
```
I could not test it that is why I did not close the issue, but I think it is solved now.
