### ISSUE TITLE
WebSocket response with No Data treated like an error in SINGLE_COMMANDS_AND_NO_VARS mode

### ISSUE THREAD

**Issue by antonyscerri** [bricaud/graphexp#52]
Hi

This may relate to a couple of other issues. There is a problem with websocket protocol and handling the responses which is effecting the SINGLE_COMMANDS_AND_NO_VARS mode. When no data is returned it treats it a bit like an error and returns without calling any provided callback routine. This is a problem when you for example make a search for some nodes based on a property value because you aren't guaranteed to have any edges between the nodes, so when it makes the call to get any edges from the matching nodes it might not return any. As a result you end up with nothing being being displayed rather than the free floating nodes.

I've tested a minimal change to simply treat it like a normal response and call the callback. You have to make some changes elsewhere so that it will handle the case where there are no edges to be added, for example in arrange_datav3 when retrieving the keyed data from "data" and checking its not null.

Tony

**Comment by bricaud** [comment]
Could you make a pull request with your modifications?

**Comment by antonyscerri** [comment]
Hi

I've put in a minimal PR which was my initial edit, this was done just so i could try using the visualisation, so its by no means been fully tested but it should give you the specific details if you want to do a more extensive test and fix or this may be sufficient for most uses.

Tony
