### ISSUE TITLE
Timeouts Loading AWS Neptune Graphs 

### ISSUE THREAD

**Issue by HarryTheHawk** [bricaud/graphexp#59]
I've been able to view tiny AWS Neptune graphs (<10 nodes/edges) using "Search", but anything larger (say 500 nodes/edges) repeatedly times out with:

_"
Can't access database using REST at http://localhost:8182
Message: timeout, timeout
Check the server configuration or try increasing the REST_TIMEOUT value in the config file.
"_

Even after cranking up the REST_TIMEOUT to 5 minutes or longer it still fails to load.

 "Get graph info" does return the graph information almost immediately however.

Any ideas on how I can troubleshoot this further?

**Comment by Auricopter** [comment]
I have no problem with about 1.000.000 nodes. (takes about 3 minutes)
But loading up to 10.000.000 nodes results in TimeLimitExceededException.
![2019-02-12 11_29_00-graphexp graph explorer](https://user-images.githubusercontent.com/1444580/52638214-bfa7d280-2ed1-11e9-809a-4c99853bb805.jpg)
