### ISSUE TITLE
3.4 compatibility

### ISSUE THREAD

**Issue by justinhauer** [bricaud/graphexp#60]
Has this been tested with gremlin server 3.4?

**Comment by teereence** [comment]
Hi
The key / value detaisls of nodes don't show, when a node is clicked on.
Though I am not fully sure it is related to 3.4, I was thinking this was due to a change in return format of g.valueMap.

Any thoughts about that?

**Comment by andrewhallambc** [comment]
We have also noticed this when connecting to tinker pop.
Neptune does show the node keys though.

BTW, we love this tool, keep up the good work folks.

**Comment by bricaud** [comment]
You are right @teereence , it comes from a change in valueMap(). It does not return any more the node properties. I am working on it. I have to modify the command in gremlin_query_nodes, inside the function click_query() within graphioGremlin.js. And maybe a few other steps processing the data. Thanks everyone for the feedback.

**Comment by smurfzilla** [comment]
Love this tool as well - am seeing the same issue with 3.4.1 - is there a milestone or projected ETA for resolution of this?

**Comment by nallbradley** [comment]
Any updates on this? Me and my team love the tool and are relying on it for graph exploration. Can we help with this? Don't want to jump on it though if @bricaud is already working it.

**Comment by bricaud** [comment]
I would be very happy to get some help on it. I can't find time at the moment to modify the code. Sorry. The gremlin query must be changed (one solution is to use valuemap() at the end of the query) and the properties returned are not in the same format.

**Comment by bricaud** [comment]
I also think I need to focus on vertex properties and  forget the idea of displaying properties of vertex properties. This seems to require a gemlin query for each property of property.

**Comment by bricaud** [comment]
I have created a branch for graphexp adapted to Gremlin 3.4 (branch g_3.4). The new query get the vertex properties for 3.4 but uses options that are not compatible with 3.3 (`.with(WithOptions.tokens)`) . so it does not work with 3.3 and earlier versions. It correctly displays vertex properties when you click on a vertex. You need to click on it twice though because the first time the properties are not there (I did not update yet the `search_query()` function that get the data in the beginning).
PR on this branch are welcome!

**Comment by bricaud** [comment]
Compatibility with gremlin 3.4 on branch g_34 has been updated. It looks good now. Could you test and report if you find bugs? If it is fine, I will merge it to the master in a week.

**Comment by Nop0x** [comment]
Can we merge this into master now?

**Comment by bricaud** [comment]
Merged
