### ISSUE TITLE
Text Contains based search crashes

### ISSUE THREAD

**Issue by teereence** [bricaud/graphexp#61]
Hi

Searching for a node by exact match works fine, but produces an error when based on g.textContains. Does this functionality require some plugins to be activated on the gremlin server side?

**Comment by bricaud** [comment]
Yes, it only works when using Janusgraph (or a variant based on Janusgraph).

**Comment by rbramley** [comment]
With TinkerPop 3.4 the equivalent is 'containing' - see http://tinkerpop.apache.org/docs/current/reference/#a-note-on-predicates 

Experimented by modifying line 119 of graphioGremlin.js accordingly and it works fine against Neptune 1.0.1.0. The correct fix would need to check if it's version 3.4 (using the GraphSON3_4 communication method).
