### ISSUE TITLE
Does this project have a roadmap

### ISSUE THREAD

**Issue by shyamremella** [bricaud/graphexp#62]
I would like to know if there is a plan with set of prioritized features for the project? I am looking for a visualization tool on janusgraph which can support some enterprise features like scale and security. 

thanks

**Comment by erandal** [comment]
Hello, i have implemented a bootstrap version of the project if you want : [https://github.com/erandal/graphexp](https://github.com/erandal/graphexp).

There is a product called https://linkurio.us/ which is not free. Very good product.
