### ISSUE TITLE
unable to connect to a configured graph 

### ISSUE THREAD

**Issue by narayana1043** [bricaud/graphexp#70]
I am using janus graph and trying to connect using the websocket connection. 

Server Address:  my ec2 address
Server Port: 8182
protocol: websocket.

I was able to connect to my graph from python notebook running on the same server and also from gremlin

This is my error msg.

Error retrieving data

No signature of method: org.janusgraph.graphdb.database.StandardJanusGraph.V() is applicable for argument types: () values: [] Possible solutions: tx(), io(org.apache.tinkerpop.gremlin.structure.io.Io$Builder), is(java.lang.Object), any(), tap(groovy.lang.Closure), use([Ljava.lang.Object;)

I am guessing i should not use the StandardJanusGraph instead use the Configured graph. can anyone help me how to fix this. 

Thank You!

**Comment by tc792617871** [comment]
hey this problem i meet too, do you have resolved it?
