### ISSUE TITLE
Missing '.' before 'fold()' - causes syntax error when clicking on a Vertex.

### ISSUE THREAD

**Issue by andrewhallambc** [bricaud/graphexp#73]
https://github.com/bricaud/graphexp/blob/49e63b3ac21b7c3fdc829f334eaa629f7f4bec16/scripts/graphioGremlin.js#L184

https://github.com/bricaud/graphexp/blob/49e63b3ac21b7c3fdc829f334eaa629f7f4bec16/scripts/graphioGremlin.js#L186

**Comment by bricaud** [comment]
How comes that no one spotted this before?
Thanks. I will make the change.

**Comment by bricaud** [comment]
should be fixed now.
Thanks
