### ISSUE TITLE
Inlinks (edges) are not shown when a node is expanded

### ISSUE THREAD

**Issue by mmpataki** [bricaud/graphexp#77]
When a node in the graph is clicked, I can see the nodes which have edge pointed to clicked node, but there is no edge shown in the graph.

I just downloaded these files as zip, extracted and opened the index.html in the browser. Now sure whether I am doing something wrong or this is a bug.

**Comment by aario** [comment]
Same here. Edges are not shown unless I click on a node and only for the selected node. I could not find any way to show all edges as in the screenshot.

**Comment by aario** [comment]
Ok. Looks like the project is abandoned for now.
The last commit is from April.
The fork that has been suggested on the readme with better UI design is not working. The issue reported for that has long been left open.
The master branch shows edges but in a wrong way and without titles.
The 0.8.0 as mentioned hear does now show edges.
The 0.7.0 does not even connect to the server. Anyone using graphexp? How did you obtain the software? Which version exactly? Does it work for you?

**Comment by aario** [comment]
Ok. Solution:
Master branch currently works. But you need to choose proper Gremlin version first. In my case it was 3.3.*. Then you need to click Get graph info and select your property to be displayed. In my case `title`. For the enhanced UI, ddmx version works https://github.com/ddmx/graphexp

**Comment by aario** [comment]
![image](https://user-images.githubusercontent.com/11817199/89742531-0bbdde00-da9b-11ea-8181-bb204cdcd553.png)

**Comment by bricaud** [comment]
Hi, thanks for your comments @aario . Good to know the problem was just the wrong Gremlin version and not something with the code. The project is not abandoned but I don't have much time to maintain it.

**Comment by mmpataki** [comment]
Just today, I started with writing my own version of this utility and I see a github notification 😄
