### ISSUE TITLE
The traversal is not happening

### ISSUE THREAD

**Issue by shekhargoat** [bricaud/graphexp#83]
I have queried a vertex by the name company and am trying to traverse through its edges by clicking on the node but nothing shows up in the UI. In the debugger console though I can see that the edges are being queried.

Please let me know if I am missing anything in the configuration. I am connecting to AWS neptune DB.

![Screenshot 2020-02-20 at 10 47 31 AM](https://user-images.githubusercontent.com/6474551/74903361-b5ff5780-53ce-11ea-8671-970b57780c8e.png)
![Screenshot 2020-02-20 at 10 46 59 AM](https://user-images.githubusercontent.com/6474551/74903365-b992de80-53ce-11ea-9195-3031e34167a8.png)

**Comment by bricaud** [comment]
Sorry, no idea. Did you find the solution?
