### ISSUE TITLE
Unable to run 'Get graph info' - error is graphioGremlin.js:313 WebSocket connection to 'ws://localhost:8182/gremlin' failed: Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by disaakdisaak** [bricaud/graphexp#85]
I have Neptune DB running and using Putty as per instructions:
When attempting to get graph info 
I've tried running with 
let server_url = "ws://"+server_address+":"+server_port+"/gremlin"
Error is graphioGremlin.js:313 WebSocket connection to 'ws://localhost:8182/gremlin' failed: Connection closed before receiving a handshake response

with code as
let server_url = "wss://"+server_address+":"+server_port+"/gremlin"
WebSocket connection to 'wss://localhost:8182/gremlin' failed: Error in connection establishment: net::ERR_CERT_COMMON_NAME_INVALID

**Comment by disaakdisaak** [comment]
This is my Putty configuration

![2020-03-12-004](https://user-images.githubusercontent.com/29784189/76561897-783b9f00-6461-11ea-9f21-e3651a1c349c.jpg)

**Comment by talwarabhimanyu** [comment]
I face the same error. Were you able to solve this? I followed the instructions on AWS's Neptune [page](https://aws.amazon.com/premiumsupport/knowledge-center/neptune-gremlin-graph-graphexp/) for connecting with GraphExp. I'm using PuTTY to create the SSH tunnel (as given in those instructions).

When I click "Get graph info" on the graphexp.html page, I see this error message in Chrome's console:
`WebSocket connection to 'ws://localhost:8182/gremlin' failed: Connection closed before receiving a handshake response`
`run_websocket_request  @  graphioGremlin.js:318`
