### ISSUE TITLE
UI rendering issue

### ISSUE THREAD

**Issue by shivaak** [bricaud/graphexp#91]
UI looks clumsy.
I'm getting the below error in console.

DevTools failed to load SourceMap: Could not load content for file:///D:/graphexp-master-bootstrap/graphexp-master/css/bootstrap.css.map: System error: net::ERR_FILE_NOT_FOUND

Attached the page snapshot for reference
![issue](https://user-images.githubusercontent.com/12840263/80787813-2da6eb00-8ba5-11ea-8b27-5fa890bdc874.jpg)

**Comment by armandleopold** [comment]
Hi Shivaak, i will look into this asap, Thanks for the report.

**Comment by danielinbaraj-cognit** [comment]
Hi, Did you get any fix for this issue please?

**Comment by armandleopold** [comment]
Yes the issue was fixed in version 0.8.4 of the docker image @danielinbaraj-cognit
