### ISSUE TITLE
Connectivity established but search doesn;t seem to work

### ISSUE THREAD

**Issue by gautam199** [bricaud/graphexp#96]
Hi,

I'm able to connect to my backend AWS Neptune database instance via REST protocol.

The "Get Graph Info" option works and results are returned correctly.

However, the "Search" feature seems to be broken. For any search query,  I get the below exception:
<img width="385" alt="CaptureNeptune" src="https://user-images.githubusercontent.com/8340727/91979095-daa39700-ed42-11ea-8d88-e45bf22f2878.PNG">

I have tried with Gremlin version 3.4/3.3 and 3.2 with the same error. Would be great if you could help fix this.

Thanks!

**Comment by jwalton922** [comment]
I am able to search against my Neptune database. I could not replicate your issue. Can you share the body of the request? It should show the query. It might be helpful to show your graphConf.js, your input into the search UI, and the console logs.

**Comment by gautam199** [comment]
Thanks for your reply.

From what I see, the query executes successfully when not passing string params. The issue seems to be with executing Gremlin queries with single quotes (for instance, when we pass in a node label as part of search criteria). I have tried escaping the quotes in multiple ways but none work. See UI below:
<img width="949" alt="GraphExp" src="https://user-images.githubusercontent.com/8340727/92192224-26f5f080-ee83-11ea-9415-e291eb4a4c0c.PNG">

Note: The Gremlin query highlighted above successfully executes when I run it in the backend, however the POST request returns the following exception in the response:

{"requestId": "<requestId>", "code": "InvalidParameterException", "detailedMessage": "body could not be parsed"}

![image](https://user-images.githubusercontent.com/8340727/92193956-29f2e000-ee87-11ea-8289-9bcdaee21319.png)


Attaching below the contents of my graphconf.js:
[graphconf.txt](https://github.com/bricaud/graphexp/files/5172278/graphconf.txt)

**Comment by jwalton922** [comment]
What version of graphexp are you using? I don't see the box for the API key that you have so I'm wondering if you've made some changes, or aren't using the latest version? 

Are you connecting directly to Neptune, or using gremlin server (or something else) as a proxy? Are you trying to get it to work with IAM authentication enabled? I don't see why that query would fail.

**Comment by gautam199** [comment]
Hi...I'm using the latest version of Graphexp (v 0.8.0). The API key I'm setting within the code  (there are some other minor local changes to do with logging etc. which can be ignored)

Yes, I'm using a proxy lambda function based on https://docs.aws.amazon.com/neptune/latest/userguide/iam-auth-connecting-python.html  exposed via API gateway. Authentication wise, the setup seems to be fine since the "GetGraphInfo" queries seem to work fine.

**Comment by jwalton922** [comment]
Since it looks like Graphexp is sending the request correctly, I would assume the issue is with the proxy. Can you disable IAM Authentication temporarily and try using the Neptune host directly from Graphexp, or log your request from your proxy?

**Comment by gautam199** [comment]
The issue does seem to be in the proxy where the POST request is being made to Neptune instance. 
Specifically, the issue seems to be with the double quotes in the Gremlin query that is part of the request payload. 

The proxy function converts 
{'gremlin': "g.V().hasLabel('PO').limit(50).toList()"}
to
{"gremlin": "g.V().hasLabel("PO").limit(50).toList()"}

which when issued against the Neptune endpoint gives 'InvalidParameterException', 'detailedMessage': 'body could not be parsed' exception.

I won't be able to debug/test it for a couple of days due to IT constraints but will update here with my findings.

Thanks @jwalton922 !

**Comment by gautam199** [comment]
The issue was in the lambda function where the quotes were an issue in the POST requests that were constructed. This is fixed now... thanks for pointing me in the right direction
