### ISSUE TITLE
graphexp cannot connect to the gremlin server with websocket

### ISSUE THREAD

**Issue by Lig5233** [bricaud/graphexp#99]
I deployed graphexp on a nginx server, and configured the server address as the gremlin service address of the production environment. The local computer is not connected to the production environment, but the nginx server can. When my local computer accesses grapexp through nginx, I see CONNECTION_ TIMED_OUT err on the browser console. So,  the connection initiated by the local computer or the nginx server? Thank you for your help.

**Comment by yinjianjie** [comment]
Have you run through this code？
